security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: INFO

spring: 
  cloud:
    services:
      registrationMethod: direct

message: Hello, Spring Cloud!
